### ISSUE TITLE
Creation error

### ISSUE THREAD

**Issue by electric-m** [huntabyte/tig-stack#14]
Hey there,

I am trying to create the stack via Portainer and get the following error:

`failed to deploy a stack: time="2023-01-03T09:53:05Z" level=warning msg="The \"GRAFANA_PORT\" variable is not set. Defaulting to a blank string." time="2023-01-03T09:53:05Z" level=warning msg="The \"DOCKER_INFLUXDB_INIT_PORT\" variable is not set. Defaulting to a blank string." open /data/compose/8/.env: no such file or directory`

Can't really tell, whats the problem here?

**Comment by maufc** [comment]
There is no .env file where those variables are defined.
Did you completly clone the repo?
