### ISSUE TITLE
Remove DOCKER_INFLUXDB_INIT_PORT from internal docker port

### ISSUE THREAD

**Issue by cornking03** [huntabyte/tig-stack#5]
The influxdb container [uses port 8086](https://hub.docker.com/_/influxdb). If the user specifies a different port for `DOCKER_INFLUXDB_INIT_HOST`, then telegraf will not be able to reach influxdb and the user will not be able to reach the influxdb ui.

### Proposed Solution:
Update [line 13](https://github.com/huntabyte/tig-stack/blob/b5a52ce9c36b3c9deb5b95ea69b34da94dd1e9a1/docker-compose.yml#L13) of `docker-compose.yml` to `- ${DOCKER_INFLUXDB_INIT_PORT}:8086`

Update [line 1005](https://github.com/huntabyte/tig-stack/blob/b5a52ce9c36b3c9deb5b95ea69b34da94dd1e9a1/telegraf/telegraf.conf#L1005) of `telegraf.conf` to `urls = ["http://${DOCKER_INFLUXDB_INIT_HOST}:8086"]`

**Comment by huntabyte** [comment]
Good catch! Feel free to submit a pull or I will adjust it soon.
